# Generated by Django 5.1 on 2024-08-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('year_published', models.IntegerField()),
                ('summary', models.TextField()),
            ],
            options={
                'db_table': 'books',
            },
        ),
    ]
